# Helper Script to Import Data from Ubisense

Script to import data from Ubisense "all rawdata" download. Reads in data, checks for any inconsistencies in tag recordings and outputs a cleaned data set for analysis. This is anticipated for use in preparing data for integration with observed data and environmental analysis.

Reads in a csv file in the following format:

`Patient, Location, from, to  `

It then cleans the data to:
- split the location data in to x and y columns
- rename the `from` `to` columns to avoid keyword conlicts 
- deletes any rows that dont start with G or R
- look for any records where start to finish are over 24 hours (since these are probably not valid or stale tags) and removes all records for that tag id
- looks at each tag record and if any have a start and finish time that are more than an hour it deletes that individual entry (sometimes tag end times are a few hours after the end of a shift)
- for each patient we look for any journeys greater than 6 hours and delete them (assumes incorrect tag allocation)
- for each patient we look for any journeys less than 15 minutes and delete them 

Finally the output is saved to csv and has the format:

`Patient, Location, starttime,	endtime,	xlocation,	ylocation, step_length `

## Initialisation

Import dependencies, create helper function, initialise some variables including loading in data. Files to import are based on the Ubisense "all rawdata" downloads from the reports section of their application interface. These are stored locally in the project "Teams" folder Data>ubisense>rawdata_smartspaces and usually have a filename such as "phase2_all_20220130.csv".

In [60]:
from matplotlib import pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import numpy as np
import datetime as dt
import math
import seaborn as sns
import scipy.stats as sps
from scipy import stats

order_list = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
order_list_noweekend = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

pd.set_option('display.max_rows', 300) # specifies number of rows to show
pd.options.display.float_format = '{:40,.4f}'.format # specifies default number format to 4 decimal places
plt.style.use('ggplot') # specifies that graphs should use ggplot styling

phase = 'P3' # edit which Phase you are analysing - this is used in graph and file generation

df = pd.read_csv('{}_raw.csv'.format(phase))
df # check what column headings in file

      Patient       Location              from                to
0       G2168  13.765,16.804  23/02/2022 10:10  23/02/2022 10:11
1       G2168  10.676,15.933  23/02/2022 10:11  23/02/2022 10:11
2       G2168    8.835,15.23  23/02/2022 10:11  23/02/2022 10:11
3       G2168    7.548,14.75  23/02/2022 10:11  23/02/2022 10:11
4       G2168   5.121,12.909  23/02/2022 10:11  23/02/2022 10:12
...       ...            ...               ...               ...
96141   R1741   19.529,3.394  06/05/2022 16:07  06/05/2022 16:07
96142   R1741   18.016,3.727  06/05/2022 16:07  06/05/2022 16:07
96143   R1741   10.431,4.622  06/05/2022 16:07  06/05/2022 16:07
96144   R1741   10.636,3.528  06/05/2022 16:07  06/05/2022 16:07
96145   R1741   11.884,3.975  06/05/2022 16:07  06/05/2022 16:08

[96146 rows x 4 columns]

## Data Cleaning and Formatting

The section below is very similar if not the same across all three phases. Key differences are called out but this is where the data is formatted for analysis.

In [61]:
df = df.dropna() # remove any rows with null values
df[['xlocation', 'ylocation']] = df['Location'].str.split(',', expand = True) # create seperate columns for the x y values
df['from'] = pd.to_datetime(df['from'], dayfirst=True) # datetime in YYYY-MM-DD HH:MM:SS format
df['to'] = pd.to_datetime(df['to'], dayfirst=True)
df.rename(columns={"from": "starttime", "to": "endtime"}, inplace=True) # renaming from and to column headings (from is a keyword)
df

,Patient,Location,starttime,endtime,xlocation,ylocation
0,G2168,"13.765,16.804",2022-02-23 10:10:00,2022-02-23 10:11:00,13.765,16.804
1,G2168,"10.676,15.933",2022-02-23 10:11:00,2022-02-23 10:11:00,10.676,15.933
2,G2168,"8.835,15.23",2022-02-23 10:11:00,2022-02-23 10:11:00,8.835,15.23
3,G2168,"7.548,14.75",2022-02-23 10:11:00,2022-02-23 10:11:00,7.548,14.75
4,G2168,"5.121,12.909",2022-02-23 10:11:00,2022-02-23 10:12:00,5.121,12.909
...,...,...,...,...,...,...
96141,R1741,"19.529,3.394",2022-05-06 16:07:00,2022-05-06 16:07:00,19.529,3.394
96142,R1741,"18.016,3.727",2022-05-06 16:07:00,2022-05-06 16:07:00,18.016,3.727
96143,R1741,"10.431,4.622",2022-05-06 16:07:00,2022-05-06 16:07:00,10.431,4.622
96144,R1741,"10.636,3.528",2022-05-06 16:07:00,2022-05-06 16:07:00,10.636,3.528
96145,R1741,"11.884,3.975",2022-05-06 16:07:00,2022-05-06 16:08:00,11.884,3.975

In [62]:
df[~df["Patient"].str.startswith(('G', 'R'))] # look for any records that dont (~) start with G or R

,Patient,Location,starttime,endtime,xlocation,ylocation
4428,Test Patient,"29.234,13.881",2022-02-23 17:34:00,2022-02-23 18:03:00,29.234,13.881
4430,Test Patient,"24.048,12.075",2022-02-23 18:03:00,2022-02-23 18:03:00,24.048,12.075
4431,Test Patient,"21.871,11.639",2022-02-23 18:03:00,2022-02-23 18:03:00,21.871,11.639
4432,Test Patient,"20.394,11.307",2022-02-23 18:03:00,2022-02-23 18:03:00,20.394,11.307
4433,Test Patient,"18.359,11.354",2022-02-23 18:03:00,2022-02-23 18:03:00,18.359,11.354
4434,Test Patient,"15.711,9.252",2022-02-23 18:03:00,2022-02-23 18:03:00,15.711,9.252
4435,Test Patient,"9.73,10.194",2022-02-23 18:03:00,2022-02-23 18:03:00,9.73,10.194
4436,Test Patient,"6.096,12",2022-02-23 18:03:00,2022-02-23 18:04:00,6.096,12

In [63]:
df = df.drop(df[~df["Patient"].str.startswith(('G', 'R'))].index) # and then drop those rows
df

,Patient,Location,starttime,endtime,xlocation,ylocation
0,G2168,"13.765,16.804",2022-02-23 10:10:00,2022-02-23 10:11:00,13.765,16.804
1,G2168,"10.676,15.933",2022-02-23 10:11:00,2022-02-23 10:11:00,10.676,15.933
2,G2168,"8.835,15.23",2022-02-23 10:11:00,2022-02-23 10:11:00,8.835,15.23
3,G2168,"7.548,14.75",2022-02-23 10:11:00,2022-02-23 10:11:00,7.548,14.75
4,G2168,"5.121,12.909",2022-02-23 10:11:00,2022-02-23 10:12:00,5.121,12.909
...,...,...,...,...,...,...
96141,R1741,"19.529,3.394",2022-05-06 16:07:00,2022-05-06 16:07:00,19.529,3.394
96142,R1741,"18.016,3.727",2022-05-06 16:07:00,2022-05-06 16:07:00,18.016,3.727
96143,R1741,"10.431,4.622",2022-05-06 16:07:00,2022-05-06 16:07:00,10.431,4.622
96144,R1741,"10.636,3.528",2022-05-06 16:07:00,2022-05-06 16:07:00,10.636,3.528
96145,R1741,"11.884,3.975",2022-05-06 16:07:00,2022-05-06 16:08:00,11.884,3.975

In [64]:
df['step_length'] = df['endtime'] - df['starttime'] # add in variable that reports the time at each step between records
print(df[df['step_length'] > pd.Timedelta(2, 'h')]) # list out any where the time iterval is greater than 2 hours for an individual step

      Patient       Location           starttime             endtime  \
4429    G2191  19.169,15.814 2022-02-23 18:01:00 2022-02-23 23:00:00
6923    G2209  13.765,16.804 2022-02-24 13:44:00 2022-02-24 22:07:00
7873    R1471    5.138,6.596 2022-02-24 16:14:00 2022-02-24 22:07:00
8010    R1475   23.279,6.087 2022-02-24 17:41:00 2022-02-24 22:10:00
10286   R1486    29.66,9.789 2022-02-25 14:38:00 2022-02-25 18:19:00
10476   R1486   19.403,15.76 2022-02-25 18:33:00 2022-02-25 23:00:00
14938   G2270  19.334,16.035 2022-02-28 19:27:00 2022-02-28 23:00:00
22474   G2328    3.782,6.577 2022-03-03 15:14:00 2022-03-03 23:00:00
23122   G2338    6.937,6.863 2022-03-04 10:12:00 2022-03-04 12:39:00
23179   G2339  14.152,17.255 2022-03-04 15:59:00 2022-03-04 23:35:00
23185   G2338  15.165,16.804 2022-03-04 17:48:00 2022-03-05 15:25:00
23189   G2339  14.165,17.781 2022-03-04 23:39:00 2022-03-05 01:44:00
23191   G2339  14.101,17.694 2022-03-05 01:44:00 2022-03-05 23:00:00
23195   G2338  15.165,16.804 2022-03-05 15:29:00 2022-03-05 23:00:00
33681   R2409    4.824,7.149 2022-03-09 16:16:00 2022-03-09 23:00:00
33779   R1583    5.304,7.312 2022-03-09 16:40:00 2022-03-09 23:00:00
36892   R1605     4.938,7.24 2022-03-10 16:27:00 2022-03-10 23:00:00
39477   R1615     4.871,6.96 2022-03-11 16:41:00 2022-03-11 23:00:00
42808   G2469    5.254,7.105 2022-03-14 16:10:00 2022-03-14 23:00:00
42845   R1631   12.036,3.528 2022-03-14 16:15:00 2022-03-14 23:00:00
42861   G2470    12.594,4.14 2022-03-14 16:19:00 2022-03-14 23:00:00
45826   G2489   6.687,14.001 2022-03-15 16:03:00 2022-03-15 23:00:00
53920   R1689  19.326,15.423 2022-03-18 18:03:00 2022-03-20 23:00:00
57742   R1714   12.036,3.528 2022-04-04 16:48:00 2022-04-04 23:00:00
59758   G4007   9.263,16.632 2022-04-05 12:33:00 2022-04-05 15:58:00
61459   G4020  29.006,17.295 2022-04-05 15:30:00 2022-04-05 23:00:00
61745   G4024  12.155,14.792 2022-04-05 16:13:00 2022-04-05 23:00:00
61813   G4026   9.088,16.935 2022-04-05 16:51:00 2022-04-05 23:00:00
70298   G4100   7.204,15.249 2022-04-11 15:44:00 2022-04-11 23:00:00
77022   G4135    6.63,14.884 2022-04-13 15:47:00 2022-04-13 23:00:00
85383   G4183   11.921,4.155 2022-04-19 15:49:00 2022-04-19 23:00:00

      xlocation ylocation     step_length
4429     19.169    15.814 0 days 04:59:00
6923     13.765    16.804 0 days 08:23:00
7873      5.138     6.596 0 days 05:53:00
8010     23.279     6.087 0 days 04:29:00
10286     29.66     9.789 0 days 03:41:00
10476    19.403     15.76 0 days 04:27:00
14938    19.334    16.035 0 days 03:33:00
22474     3.782     6.577 0 days 07:46:00
23122     6.937     6.863 0 days 02:27:00
23179    14.152    17.255 0 days 07:36:00
23185    15.165    16.804 0 days 21:37:00
23189    14.165    17.781 0 days 02:05:00
23191    14.101    17.694 0 days 21:16:00
23195    15.165    16.804 0 days 07:31:00
33681     4.824     7.149 0 days 06:44:00
33779     5.304     7.312 0 days 06:20:00
36892     4.938      7.24 0 days 06:33:00
39477     4.871      6.96 0 days 06:19:00
42808     5.254     7.105 0 days 06:50:00
42845    12.036     3.528 0 days 06:45:00
42861    12.594      4.14 0 days 06:41:00
45826     6.687    14.001 0 days 06:57:00
53920    19.326    15.423 2 days 04:57:00
57742    12.036     3.528 0 days 06:12:00
59758     9.263    16.632 0 days 03:25:00
61459    29.006    17.295 0 days 07:30:00
61745    12.155    14.792 0 days 06:47:00
61813     9.088    16.935 0 days 06:09:00
70298     7.204    15.249 0 days 07:16:00
77022      6.63    14.884 0 days 07:13:00
85383    11.921     4.155 0 days 07:11:00

In [65]:
print(df[df['step_length'] < pd.Timedelta(0, 'h')]) # list out any where the time iterval is greater than 2 hours for an individual step

Empty DataFrame
Columns: [Patient, Location, starttime, endtime, xlocation, ylocation, step_length]
Index: []

In [66]:
df[df['Patient'] == 'R0651'] # If you want to check data before deletion, use this function to check to see the record that seems to be too long

Empty DataFrame
Columns: [Patient, Location, starttime, endtime, xlocation, ylocation, step_length]
Index: []

In [67]:
df = df.drop(df[df['step_length'] > pd.Timedelta(2, 'h')].index) # remove any individual step records that are more than 2 hours
df = df.drop(df[df['step_length'] < pd.Timedelta(0, 'h')].index) # remove any individual step records that are more than 2 hours

In [68]:
# check the start and end dates of the phase being reported yyyy-mmm-dd
print("Earliest Date: ", df.starttime.min())
print("Latest Date:   ", df.endtime.max())

Earliest Date:  2022-02-23 10:10:00
Latest Date:    2022-05-06 16:08:00

In [69]:
df.nsmallest(10, 'step_length')

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
1,G2168,"10.676,15.933",2022-02-23 10:11:00,2022-02-23 10:11:00,10.676,15.933,0 days
2,G2168,"8.835,15.23",2022-02-23 10:11:00,2022-02-23 10:11:00,8.835,15.23,0 days
3,G2168,"7.548,14.75",2022-02-23 10:11:00,2022-02-23 10:11:00,7.548,14.75,0 days
5,R1439,"5.138,6.596",2022-02-23 10:11:00,2022-02-23 10:11:00,5.138,6.596,0 days
7,R1439,"6.218,5.866",2022-02-23 10:12:00,2022-02-23 10:12:00,6.218,5.866,0 days
8,R1439,"7.271,6.108",2022-02-23 10:12:00,2022-02-23 10:12:00,7.271,6.108,0 days
9,R1439,"6.509,6.82",2022-02-23 10:12:00,2022-02-23 10:12:00,6.509,6.82,0 days
10,G2168,"5.11,11.553",2022-02-23 10:12:00,2022-02-23 10:12:00,5.11,11.553,0 days
11,R1439,"7.353,5.633",2022-02-23 10:12:00,2022-02-23 10:12:00,7.353,5.633,0 days
12,G2168,"5.846,10.72",2022-02-23 10:12:00,2022-02-23 10:12:00,5.846,10.72,0 days

In [70]:
df.sort_values(by=['starttime'])

,Patient,Location,starttime,endtime,xlocation,ylocation,step_length
0,G2168,"13.765,16.804",2022-02-23 10:10:00,2022-02-23 10:11:00,13.765,16.804,0 days 00:01:00
1,G2168,"10.676,15.933",2022-02-23 10:11:00,2022-02-23 10:11:00,10.676,15.933,0 days 00:00:00
2,G2168,"8.835,15.23",2022-02-23 10:11:00,2022-02-23 10:11:00,8.835,15.23,0 days 00:00:00
3,G2168,"7.548,14.75",2022-02-23 10:11:00,2022-02-23 10:11:00,7.548,14.75,0 days 00:00:00
4,G2168,"5.121,12.909",2022-02-23 10:11:00,2022-02-23 10:12:00,5.121,12.909,0 days 00:01:00
...,...,...,...,...,...,...,...
96141,R1741,"19.529,3.394",2022-05-06 16:07:00,2022-05-06 16:07:00,19.529,3.394,0 days 00:00:00
96142,R1741,"18.016,3.727",2022-05-06 16:07:00,2022-05-06 16:07:00,18.016,3.727,0 days 00:00:00
96143,R1741,"10.431,4.622",2022-05-06 16:07:00,2022-05-06 16:07:00,10.431,4.622,0 days 00:00:00
96144,R1741,"10.636,3.528",2022-05-06 16:07:00,2022-05-06 16:07:00,10.636,3.528,0 days 00:00:00
96145,R1741,"11.884,3.975",2022-05-06 16:07:00,2022-05-06 16:08:00,11.884,3.975,0 days 00:01:00

In [71]:
df.dtypes # list out the updated column names and data types

Patient                 object
Location                object
starttime       datetime64[ns]
endtime         datetime64[ns]
xlocation               object
ylocation               object
step_length    timedelta64[ns]
dtype: object

## Create a new dataframe to group each patient id

The code belows gets the earliest and latest times from a patient allowing the total journey time to be tracked.

In [72]:
dfgrouped = df.groupby('Patient', as_index = False).agg(
    {'starttime': ['min'], 'endtime': ['max'], 'xlocation': ['first'], 'ylocation': ['first']})
dfgrouped

    Patient           starttime             endtime xlocation ylocation
                            min                 max     first     first
0     G1638 2022-03-15 11:15:00 2022-03-15 12:37:00     3.738     6.596
1     G2168 2022-02-23 10:10:00 2022-02-23 11:02:00    13.765    16.804
2     G2169 2022-02-23 10:14:00 2022-02-23 11:24:00    13.765    16.804
3     G2170 2022-02-23 10:15:00 2022-02-23 11:31:00    18.524    14.793
4     G2171 2022-02-23 10:22:00 2022-02-23 12:01:00    13.765    16.804
..      ...                 ...                 ...       ...       ...
995   R4097 2022-04-20 13:42:00 2022-04-20 14:08:00    11.835     4.174
996   R4098 2022-04-21 10:20:00 2022-04-21 10:46:00    12.057     4.246
997   R4099 2022-04-21 10:45:00 2022-04-21 11:46:00    12.121     3.847
998   R4100 2022-04-21 13:40:00 2022-04-21 14:30:00    11.948     3.835
999   R4101 2022-04-21 12:10:00 2022-04-21 13:24:00     6.669      7.21

[1000 rows x 5 columns]

The code below changes column headers and continues to format and clean the data for subsequent analysis.

In [73]:
flat_cols = []
for i in dfgrouped.columns:
    flat_cols.append(i[0]) # take the first element of the column heading only (ie ignore min, max, first)
dfgrouped.columns = flat_cols

Add in length of journey to each grouped patient id

In [74]:
dfgrouped['visit_length'] = dfgrouped['endtime'] - dfgrouped['starttime']

In [75]:
dfgrouped

,Patient,starttime,endtime,xlocation,ylocation,visit_length
0,G1638,2022-03-15 11:15:00,2022-03-15 12:37:00,3.738,6.596,0 days 01:22:00
1,G2168,2022-02-23 10:10:00,2022-02-23 11:02:00,13.765,16.804,0 days 00:52:00
2,G2169,2022-02-23 10:14:00,2022-02-23 11:24:00,13.765,16.804,0 days 01:10:00
3,G2170,2022-02-23 10:15:00,2022-02-23 11:31:00,18.524,14.793,0 days 01:16:00
4,G2171,2022-02-23 10:22:00,2022-02-23 12:01:00,13.765,16.804,0 days 01:39:00
...,...,...,...,...,...,...
995,R4097,2022-04-20 13:42:00,2022-04-20 14:08:00,11.835,4.174,0 days 00:26:00
996,R4098,2022-04-21 10:20:00,2022-04-21 10:46:00,12.057,4.246,0 days 00:26:00
997,R4099,2022-04-21 10:45:00,2022-04-21 11:46:00,12.121,3.847,0 days 01:01:00
998,R4100,2022-04-21 13:40:00,2022-04-21 14:30:00,11.948,3.835,0 days 00:50:00
999,R4101,2022-04-21 12:10:00,2022-04-21 13:24:00,6.669,7.21,0 days 01:14:00

# Delete Outlier Patient Journeys
Check to see if there are any groups of patient records that are over 1 day in length and then remove them from data frame. Assumption here is that if tag timings are greater than 24 hours it is a tag that has been aborted, lost or forgotton about. NOTE: this will remove any records where the same Patient ID has been used twice.

In [76]:
print(dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(1, 'd')]) # list out the ones to be deleted

    Patient           starttime             endtime xlocation ylocation  \
150   G2338 2022-03-04 10:12:00 2022-03-05 15:29:00     4.851     7.042

       visit_length
150 1 days 05:17:00

In [77]:
dfgrouped = dfgrouped.drop(dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(1, 'd')].index) # delete those over 1 day

In [78]:
dfgrouped['visit_length'].max() # check to see what max length of visit is after first cull

Timedelta('0 days 20:02:00')

Check to see if there are any tags that have been left unchecked at end of day - and delete those records from main dataframe. NOTE: could try and delete the readings that are overnight but difficult pattern to identify - since low percentage of results, just delete - think these are tags that are not checked back in properly?

In [79]:
dfgrouped[dfgrouped['visit_length'] > pd.Timedelta(6, 'h')] # check to see how many patient journeys are over 6 hours - probably not valid so delete

,Patient,starttime,endtime,xlocation,ylocation,visit_length
151,G2339,2022-03-04 12:39:00,2022-03-05 01:44:00,10.76,12.443,0 days 13:05:00
778,R1605,2022-03-10 15:51:00,2022-03-11 11:53:00,5.017,3.522,0 days 20:02:00

In [80]:
dfgrouped = dfgrouped.drop(dfgrouped[dfgrouped['endtime'] - dfgrouped['starttime'] > pd.Timedelta(6, 'h')].index) # delete those over 5 hours

Check to see how many patient journeys are implausibly short - ie under 15 minutes - and delete those.

In [81]:
dfgrouped['visit_length'].min() # check to see what min length of visit is after first cull

Timedelta('0 days 00:01:00')

In [82]:
dfgrouped[dfgrouped['visit_length'] < pd.Timedelta(15, 'm')] # check to see how many patient journeys are under 15 mins - probably not valid so delete

,Patient,starttime,endtime,xlocation,ylocation,visit_length
123,G2306,2022-03-01 15:53:00,2022-03-01 15:55:00,12.855,16.07,0 days 00:02:00
237,G2430,2022-03-11 10:16:00,2022-03-11 10:20:00,12.036,3.528,0 days 00:04:00
330,G2528,2022-03-17 11:48:00,2022-03-17 11:57:00,19.009,15.926,0 days 00:09:00
382,G2583,2022-05-04 11:06:00,2022-05-04 11:17:00,4.804,7.276,0 days 00:11:00
452,G4056,2022-04-08 15:03:00,2022-04-08 15:16:00,6.446,6.211,0 days 00:13:00
484,G4093,2022-04-11 12:40:00,2022-04-11 12:47:00,5.138,6.596,0 days 00:07:00
540,G4149,2022-04-14 11:57:00,2022-04-14 11:58:00,6.439,7.732,0 days 00:01:00
638,R1451,2022-02-23 14:58:00,2022-02-23 15:00:00,18.524,14.793,0 days 00:02:00
649,R1465,2022-02-24 11:42:00,2022-02-24 11:45:00,13.765,16.804,0 days 00:03:00
696,R1514,2022-03-02 10:17:00,2022-03-02 10:22:00,12.036,3.528,0 days 00:05:00
703,R1522,2022-03-02 11:44:00,2022-03-02 11:49:00,4.828,7.196,0 days 00:05:00
733,R1557,2022-03-08 10:54:00,2022-03-08 10:55:00,5.138,6.596,0 days 00:01:00
910,R4004,2022-04-05 10:51:00,2022-04-05 11:03:00,12.036,3.528,0 days 00:12:00
932,R4026,2022-04-08 14:44:00,2022-04-08 14:46:00,5.138,6.596,0 days 00:02:00
966,R4066,2022-04-13 12:17:00,2022-04-13 12:18:00,12.036,3.528,0 days 00:01:00

In [83]:
dfgrouped = dfgrouped.drop(dfgrouped[dfgrouped['endtime'] - dfgrouped['starttime'] < pd.Timedelta(15, 'm')].index) # delete those under 15 min

In [84]:
dfgrouped

,Patient,starttime,endtime,xlocation,ylocation,visit_length
0,G1638,2022-03-15 11:15:00,2022-03-15 12:37:00,3.738,6.596,0 days 01:22:00
1,G2168,2022-02-23 10:10:00,2022-02-23 11:02:00,13.765,16.804,0 days 00:52:00
2,G2169,2022-02-23 10:14:00,2022-02-23 11:24:00,13.765,16.804,0 days 01:10:00
3,G2170,2022-02-23 10:15:00,2022-02-23 11:31:00,18.524,14.793,0 days 01:16:00
4,G2171,2022-02-23 10:22:00,2022-02-23 12:01:00,13.765,16.804,0 days 01:39:00
...,...,...,...,...,...,...
995,R4097,2022-04-20 13:42:00,2022-04-20 14:08:00,11.835,4.174,0 days 00:26:00
996,R4098,2022-04-21 10:20:00,2022-04-21 10:46:00,12.057,4.246,0 days 00:26:00
997,R4099,2022-04-21 10:45:00,2022-04-21 11:46:00,12.121,3.847,0 days 01:01:00
998,R4100,2022-04-21 13:40:00,2022-04-21 14:30:00,11.948,3.835,0 days 00:50:00
999,R4101,2022-04-21 12:10:00,2022-04-21 13:24:00,6.669,7.21,0 days 01:14:00

In [85]:
# make a copy of records (df3) from df that have an equivalent Patient id in dfgrouped
df3 = df[df['Patient'].isin(dfgrouped['Patient'])]  
print('start record count: ', df.Patient.count())
print('clean record count: ', df3.Patient.count())

start record count:  96107
clean record count:  95742

# Export back to clean csv
Assumes user will then move to appropriate "clean data" folder so just using generic output.csv filename.

In [86]:
df3.to_csv('{}_input.csv'.format(phase), index=False) # note use subset of records in df3

To end, print out some patient journey stats for info!

In [87]:
dfgrouped['visit_length'].describe()

count                          982
mean     0 days 01:07:29.205702647
std      0 days 00:26:13.562927206
min                0 days 00:19:00
25%                0 days 00:50:00
50%                0 days 01:04:00
75%                0 days 01:20:00
max                0 days 04:38:00
Name: visit_length, dtype: object

End